module.exports = {
    LOG_INVALID_LEVEL: 'LOG_INVALID_LEVEL',
    MISSING_DISCORD_TOKEN: 'MISSING_DISCORD_TOKEN',
    DATASTORE_FAILED_RUN: 'DATASTORE_FAILED_RUN',
    INVALID_DATASTORE: 'INVALID_DATASTORE',
    MANAGER_FAILED_RUN: 'MANAGER_FAILED_RUN',
    INVALID_MANAGER: 'INVALID_MANAGER',
    FIND_PLUGIN_NOT_A_DIR: 'FIND_PLUGIN_NOT_A_DIR',
    NOT_A_PLUGIN: 'NOT_A_PLUGIN',
    PLUGIN_MISSING_DEPENDENCIES: 'PLUGIN_MISSING_DEPENDENCIES',
    PLUGIN_MISSING_PARENT: 'PLUGIN_MISSING_PARENT',
    PLUGIN_FAILED_RUN: 'PLUGIN_FAILED_RUN'
};