module.exports = {
    ASSERTION_ERROR: 'ASSERTION_ERROR',
    LOG_INVALID_LEVEL: 'LOG_INVALID_LEVEL',
    REQUEST_MANAGER_UNAVAILABLE: 'REQUEST_MANAGER_UNAVAILABLE',
    MISSING_CALLBACK_HANDLER: 'MISSING_CALLBACK_HANDLER',
    CALLBACK_REQUEST_TIMED_OUT: 'CALLBACK_REQUEST_TIMED_OUT',
    PLAYER_NO_DISCORD_ID: 'PLAYER_NO_DISCORD_ID',
    LOAD_PLAYER_TOTAL_FAILURE: 'LOAD_PLAYER_TOTAL_FAILURE'
};